# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ori_ui/login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ui_img.login_images_rc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowTitle("基于YOLOv8的检测演示软件V1.0")
        Form.resize(800, 600)
        Form.setStyleSheet("QWidget#Form{background-image: url(:/login_background/login.JPG);}")


        self.edit_username = QtWidgets.QLineEdit(Form)
        self.edit_username.setGeometry(QtCore.QRect(250, 200, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.edit_username.setFont(font)
        self.edit_username.setObjectName("edit_username")

        self.btn_login = QtWidgets.QPushButton(Form)
        self.btn_login.setGeometry(QtCore.QRect(220, 430, 120, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")

        self.edit_password = QtWidgets.QLineEdit(Form)
        self.edit_password.setGeometry(QtCore.QRect(250, 300, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.edit_password.setFont(font)
        self.edit_password.setObjectName("edit_password")

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 80, 781, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")

        self.btn_regeist = QtWidgets.QPushButton(Form)
        self.btn_regeist.setGeometry(QtCore.QRect(420, 430, 120, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.btn_regeist.setFont(font)
        self.btn_regeist.setObjectName("btn_regeist")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.edit_username.setPlaceholderText(_translate("Form", "用户名"))
        self.btn_login.setText(_translate("Form", "登录"))
        self.edit_password.setPlaceholderText(_translate("Form", "密码"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; color:#ffffff;\">基于YOLOv8的检测演示软件</span></p></body></html>"))
        self.btn_regeist.setText(_translate("Form", "注册"))

