# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ori_ui/registe_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ui_img.registe_images_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowTitle("基于YOLOv8的检测演示软件V1.0")
        Dialog.resize(800, 600)
        Dialog.setStyleSheet("QDialog#Dialog{background-image: url(:/registe_background/registe.JPG);}\n"
                             "")


        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 120, 241, 81))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")

        self.edit_password = QtWidgets.QLineEdit(Dialog)
        self.edit_password.setGeometry(QtCore.QRect(260, 320, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.edit_password.setFont(font)
        self.edit_password.setObjectName("edit_password")

        self.pushButton_regiser = QtWidgets.QPushButton(Dialog)
        self.pushButton_regiser.setGeometry(QtCore.QRect(220, 410, 120, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.pushButton_regiser.setFont(font)
        self.pushButton_regiser.setObjectName("pushButton_regiser")

        self.edit_username = QtWidgets.QLineEdit(Dialog)
        self.edit_username.setGeometry(QtCore.QRect(260, 230, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.edit_username.setFont(font)
        self.edit_username.setObjectName("edit_username")

        self.pushButton_cancer = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancer.setGeometry(QtCore.QRect(420, 410, 120, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.pushButton_cancer.setFont(font)
        self.pushButton_cancer.setObjectName("pushButton_cancer")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; color:#ffffff;\">账号注册</span></p></body></html>"))
        self.edit_password.setPlaceholderText(_translate("Dialog", "设置密码"))
        self.pushButton_regiser.setText(_translate("Dialog", "注册"))
        self.edit_username.setPlaceholderText(_translate("Dialog", "注册账号"))
        self.pushButton_cancer.setText(_translate("Dialog", "取消"))

